"""add queries table

Revision ID: efdc324e9885
Revises: 
Create Date: 2026-04-07 13:47:31.239249
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = 'efdc324e9885'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='querystatus'), nullable=False),
    sa.Column('snowflake_query_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result_rows', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_snowflake_query_id'), 'queries', ['snowflake_query_id'], unique=False)
    op.create_index(op.f('ix_queries_status'), 'queries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queries_status'), table_name='queries')
    op.drop_index(op.f('ix_queries_snowflake_query_id'), table_name='queries')
    op.drop_table('queries')
    # ### end Alembic commands ###
